<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseSortableArticleUniqueBy
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 * @property string $category_id
 * @property SortableArticleCategory $Category
 * @property string $id
 *
 * @method string                  getName($load = true) Returns the current record's "name" value
 * @method string                  getCategoryId($load = true) Returns the current record's "category_id" value
 * @method SortableArticleCategory getCategory($load = true) Returns the current record's "Category" value
 * @method string                  getId($load = true) Returns the current record's "id" value
 * @method SortableArticleUniqueBy setName($value, $load = true) Sets the current record's "name" value
 * @method SortableArticleUniqueBy setCategoryId($value, $load = true) Sets the current record's "category_id" value
 * @method SortableArticleUniqueBy setCategory($value, $load = true) Sets the current record's "Category" value
 * @method SortableArticleUniqueBy setId($value, $load = true) Sets the current record's "id" value
 *
 */
abstract class BaseSortableArticleUniqueBy extends sfDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('sortable_article_unique_by');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SortableArticleCategory as Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $sortable0 = new Doctrine_Template_Sortable(array(
             'uniqueBy' =>
             array(
              0 => 'category_id',
             ),
             ));
        $this->actAs($sortable0);
    }

}