<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseSortableArticle
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 * @property string $id
 *
 * @method string          getName($load = true) Returns the current record's "name" value
 * @method string          getId($load = true) Returns the current record's "id" value
 * @method SortableArticle setName($value, $load = true) Sets the current record's "name" value
 * @method SortableArticle setId($value, $load = true) Sets the current record's "id" value
 *
 */
abstract class BaseSortableArticle extends sfDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('sortable_article');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sortable0 = new Doctrine_Template_Sortable();
        $this->actAs($sortable0);
    }

}