<?php

declare(strict_types=1);

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseSortableArticleCategory
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $id
 * @property string $name
 * @property Doctrine_Collection $SortableArticleUniqueBy
 *
 */
abstract class BaseSortableArticleCategory extends sfDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('sortable_article_category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SortableArticleUniqueBy', [
             'local' => 'id',
             'foreign' => 'category_id']);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param string $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getName($load = true)
    {
        return $this->_get('name', $load);
    }

    /**
     * @param string $name
     * @param bool $load
     *
     * @return self
     */
    public function setName($name, $load = true)
    {
        return $this->_set('name', $name, $load);
    }

    /**
     * @param bool $load
     *
     * @return Doctrine_Collection
     */
    public function getSortableArticleUniqueBy($load = true)
    {
        return $this->_get('SortableArticleUniqueBy', $load);
    }

    /**
     * @param Doctrine_Collection $SortableArticleUniqueBy
     * @param bool $load
     *
     * @return self
     */
    public function setSortableArticleUniqueBy($SortableArticleUniqueBy, $load = true)
    {
        return $this->_set('SortableArticleUniqueBy', $SortableArticleUniqueBy, $load);
    }

}