<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseSortableArticleCategory
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $id
 * @property string $name
 * @property Doctrine_Collection $SortableArticleUniqueBy
 *
 * @method string                  getId($load = true)          Returns the current record's "id" value
 * @method string                  getName($load = true)        Returns the current record's "name" value
 * @method Doctrine_Collection     getSortableArticleUniqueBy($load = true) Returns the current record's "SortableArticleUniqueBy" collection
 * @method SortableArticleCategory setId($value, $load = true)  Sets the current record's "id" value
 * @method SortableArticleCategory setName($value, $load = true) Sets the current record's "name" value
 * @method SortableArticleCategory setSortableArticleUniqueBy($value, $load = true) Sets the current record's "SortableArticleUniqueBy" collection
 *
 */
abstract class BaseSortableArticleCategory extends sfDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('sortable_article_category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SortableArticleUniqueBy', [
             'local' => 'id',
             'foreign' => 'category_id']);
    }

}