<?php

declare(strict_types=1);

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseSortableArticleUniqueBy
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 * @property string $category_id
 * @property SortableArticleCategory $Category
 * @property string $id
 *
 */
abstract class BaseSortableArticleUniqueBy extends sfDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('sortable_article_unique_by');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SortableArticleCategory as Category', [
             'local' => 'category_id',
             'foreign' => 'id']);

        $sortable0 = new Doctrine_Template_Sortable(array(
             'uniqueBy' =>
             array(
              0 => 'category_id',
             ),
             ));
        $this->actAs($sortable0);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getName($load = true)
    {
        return $this->_get('name', $load);
    }

    /**
     * @param string $name
     * @param bool $load
     *
     * @return self
     */
    public function setName($name, $load = true)
    {
        return $this->_set('name', $name, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getCategoryId($load = true)
    {
        return $this->_get('category_id', $load);
    }

    /**
     * @param string $category_id
     * @param bool $load
     *
     * @return self
     */
    public function setCategoryId($category_id, $load = true)
    {
        return $this->_set('category_id', $category_id, $load);
    }

    /**
     * @param bool $load
     *
     * @return SortableArticleCategory
     */
    public function getCategory($load = true)
    {
        return $this->_get('Category', $load);
    }

    /**
     * @param SortableArticleCategory $Category
     * @param bool $load
     *
     * @return self
     */
    public function setCategory($Category, $load = true)
    {
        return $this->_set('Category', $Category, $load);
    }

    /**
     * @param bool $load
     *
     * @return integer
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param integer $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

}