<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseBlogArticle
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property BlogAuthor $Author
 * @property string $id
 *
 */
abstract class BaseBlogArticle extends Article
{

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BlogAuthor as Author', [
             'local' => 'blog_author_id',
             'foreign' => 'id']);
    }

    /**
     * @param bool $load
     *
     * @return BlogAuthor
     */
    public function getAuthor($load = true)
    {
        return $this->_get('Author', $load);
    }

    /**
     * @param BlogAuthor $Author
     * @param bool $load
     *
     * @return self
     */
    public function setAuthor($Author, $load = true)
    {
        return $this->_set('Author', $Author, $load);
    }

    /**
     * @param bool $load
     *
     * @return integer
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param integer $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

}