<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseUserGroup
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $user_id
 * @property string $group_id
 *
 */
abstract class BaseUserGroup extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('user_group');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getUserId($load = true)
    {
        return $this->_get('user_id', $load);
    }

    /**
     * @param string $user_id
     * @param bool $load
     *
     * @return self
     */
    public function setUserId($user_id, $load = true)
    {
        return $this->_set('user_id', $user_id, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getGroupId($load = true)
    {
        return $this->_get('group_id', $load);
    }

    /**
     * @param string $group_id
     * @param bool $load
     *
     * @return self
     */
    public function setGroupId($group_id, $load = true)
    {
        return $this->_set('group_id', $group_id, $load);
    }

}