<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseCamelCase
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $article_id
 * @property string $testCamelCase
 * @property Article $Article
 * @property string $id
 *
 * @method string    getArticleId($load = true) Returns the current record's "article_id" value
 * @method string    getTestCamelCase($load = true) Returns the current record's "testCamelCase" value
 * @method Article   getArticle($load = true) Returns the current record's "Article" value
 * @method string    getId($load = true) Returns the current record's "id" value
 * @method CamelCase setArticleId($value, $load = true) Sets the current record's "article_id" value
 * @method CamelCase setTestCamelCase($value, $load = true) Sets the current record's "testCamelCase" value
 * @method CamelCase setArticle($value, $load = true) Sets the current record's "Article" value
 * @method CamelCase setId($value, $load = true) Sets the current record's "id" value
 *
 */
abstract class BaseCamelCase extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('camel_case');
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('testCamelCase', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', [
             'local' => 'article_id',
             'foreign' => 'id']);
    }

}