<?php

declare(strict_types=1);

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseResourceType
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $id
 * @property string $name
 *
 */
abstract class BaseResourceType extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('resource_type');
        $this->hasColumn('id', 'enum', null, array(
             'type' => 'enum',
             'values' =>
             array(
              0 => 'type1',
              1 => 'type2',
              2 => 'type3',
             ),
             'primary' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param string $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getName($load = true)
    {
        return $this->_get('name', $load);
    }

    /**
     * @param string $name
     * @param bool $load
     *
     * @return self
     */
    public function setName($name, $load = true)
    {
        return $this->_set('name', $name, $load);
    }

}