<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseAuthorInheritance
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $id
 *
 */
abstract class BaseAuthorInheritance extends Author
{

    public function setUp()
    {
        parent::setUp();
        
    }

    /**
     * @param bool $load
     *
     * @return integer
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param integer $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

}