<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BasePermission
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $Groups
 * @property string $id
 *
 */
abstract class BasePermission extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('permission');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User as Users', [
             'refClass' => 'UserPermission',
             'local' => 'permission_id',
             'foreign' => 'user_id']);

        $this->hasMany('Group as Groups', [
             'refClass' => 'GroupPermission',
             'local' => 'permission_id',
             'foreign' => 'group_id']);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getName($load = true)
    {
        return $this->_get('name', $load);
    }

    /**
     * @param string $name
     * @param bool $load
     *
     * @return self
     */
    public function setName($name, $load = true)
    {
        return $this->_set('name', $name, $load);
    }

    /**
     * @param bool $load
     *
     * @return Doctrine_Collection
     */
    public function getUsers($load = true)
    {
        return $this->_get('Users', $load);
    }

    /**
     * @param Doctrine_Collection $Users
     * @param bool $load
     *
     * @return self
     */
    public function setUsers($Users, $load = true)
    {
        return $this->_set('Users', $Users, $load);
    }

    /**
     * @param bool $load
     *
     * @return Doctrine_Collection
     */
    public function getGroups($load = true)
    {
        return $this->_get('Groups', $load);
    }

    /**
     * @param Doctrine_Collection $Groups
     * @param bool $load
     *
     * @return self
     */
    public function setGroups($Groups, $load = true)
    {
        return $this->_set('Groups', $Groups, $load);
    }

    /**
     * @param bool $load
     *
     * @return integer
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param integer $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

}