<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseAuthorInheritanceConcrete
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $additional
 * @property string $id
 *
 * @method string                    getAdditional($load = true) Returns the current record's "additional" value
 * @method string                    getId($load = true) Returns the current record's "id" value
 * @method AuthorInheritanceConcrete setAdditional($value, $load = true) Sets the current record's "additional" value
 * @method AuthorInheritanceConcrete setId($value, $load = true) Sets the current record's "id" value
 *
 */
abstract class BaseAuthorInheritanceConcrete extends Author
{

    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('author_inheritance_concrete');
        $this->hasColumn('additional', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setSubclasses($map)
    {
        $this->setTableName('author_inheritance_concrete');

        parent::setSubclasses($map);
    }

    public function setUp()
    {
        parent::setUp();
        
    }

}