<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseAuthorInheritance
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $id
 *
 * @method string            getId($load = true) Returns the current record's "id" value
 * @method AuthorInheritance setId($value, $load = true) Sets the current record's "id" value
 *
 */
abstract class BaseAuthorInheritance extends Author
{

    public function setUp()
    {
        parent::setUp();
        
    }

}