<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseGroupPermission
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $group_id
 * @property string $permission_id
 *
 * @method string          getGroupId($load = true) Returns the current record's "group_id" value
 * @method string          getPermissionId($load = true) Returns the current record's "permission_id" value
 * @method GroupPermission setGroupId($value, $load = true) Sets the current record's "group_id" value
 * @method GroupPermission setPermissionId($value, $load = true) Sets the current record's "permission_id" value
 *
 */
abstract class BaseGroupPermission extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('group_permission');
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('permission_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }

}