<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseProfile
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $user_id
 * @property string $first_name
 * @property string $last_name
 * @property User $User
 * @property string $id
 *
 */
abstract class BaseProfile extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('profile');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', [
             'local' => 'user_id',
             'foreign' => 'id']);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getUserId($load = true)
    {
        return $this->_get('user_id', $load);
    }

    /**
     * @param string $user_id
     * @param bool $load
     *
     * @return self
     */
    public function setUserId($user_id, $load = true)
    {
        return $this->_set('user_id', $user_id, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getFirstName($load = true)
    {
        return $this->_get('first_name', $load);
    }

    /**
     * @param string $first_name
     * @param bool $load
     *
     * @return self
     */
    public function setFirstName($first_name, $load = true)
    {
        return $this->_set('first_name', $first_name, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getLastName($load = true)
    {
        return $this->_get('last_name', $load);
    }

    /**
     * @param string $last_name
     * @param bool $load
     *
     * @return self
     */
    public function setLastName($last_name, $load = true)
    {
        return $this->_set('last_name', $last_name, $load);
    }

    /**
     * @param bool $load
     *
     * @return User
     */
    public function getUser($load = true)
    {
        return $this->_get('User', $load);
    }

    /**
     * @param User $User
     * @param bool $load
     *
     * @return self
     */
    public function setUser($User, $load = true)
    {
        return $this->_set('User', $User, $load);
    }

    /**
     * @param bool $load
     *
     * @return integer
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param integer $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

}