<?php

declare(strict_types=1);

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseAuthor
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 * @property string $type
 * @property Doctrine_Collection $Articles
 * @property string $id
 *
 */
abstract class BaseAuthor extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('author');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->setSubClasses(array(
             'AuthorInheritance' =>
             array(
              'type' => 'AuthorInheritance',
             ),
             'BlogAuthor' =>
             array(
              'type' => 'BlogAuthor',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Article as Articles', [
             'local' => 'id',
             'foreign' => 'author_id']);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getName($load = true)
    {
        return $this->_get('name', $load);
    }

    /**
     * @param string $name
     * @param bool $load
     *
     * @return self
     */
    public function setName($name, $load = true)
    {
        return $this->_set('name', $name, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getType($load = true)
    {
        return $this->_get('type', $load);
    }

    /**
     * @param string $type
     * @param bool $load
     *
     * @return self
     */
    public function setType($type, $load = true)
    {
        return $this->_set('type', $type, $load);
    }

    /**
     * @param bool $load
     *
     * @return Doctrine_Collection
     */
    public function getArticles($load = true)
    {
        return $this->_get('Articles', $load);
    }

    /**
     * @param Doctrine_Collection $Articles
     * @param bool $load
     *
     * @return self
     */
    public function setArticles($Articles, $load = true)
    {
        return $this->_set('Articles', $Articles, $load);
    }

    /**
     * @param bool $load
     *
     * @return integer
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param integer $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

}