<?php

declare(strict_types=1);

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseModelWithNumberInColumn
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $column_1
 * @property string $column2
 * @property string $column__3
 * @property string $id
 *
 */
abstract class BaseModelWithNumberInColumn extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('model_with_number_in_column');
        $this->hasColumn('column_1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('column2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('column__3', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getColumn1($load = true)
    {
        return $this->_get('column_1', $load);
    }

    /**
     * @param string $column_1
     * @param bool $load
     *
     * @return self
     */
    public function setColumn1($column_1, $load = true)
    {
        return $this->_set('column_1', $column_1, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getColumn2($load = true)
    {
        return $this->_get('column2', $load);
    }

    /**
     * @param string $column2
     * @param bool $load
     *
     * @return self
     */
    public function setColumn2($column2, $load = true)
    {
        return $this->_set('column2', $column2, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getColumn_3($load = true)
    {
        return $this->_get('column__3', $load);
    }

    /**
     * @param string $column__3
     * @param bool $load
     *
     * @return self
     */
    public function setColumn_3($column__3, $load = true)
    {
        return $this->_set('column__3', $column__3, $load);
    }

    /**
     * @param bool $load
     *
     * @return integer
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param integer $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

}