<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseBlogArticle
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property BlogAuthor $Author
 * @property string $id
 *
 * @method BlogAuthor  getAuthor($load = true) Returns the current record's "Author" value
 * @method string      getId($load = true) Returns the current record's "id" value
 * @method BlogArticle setAuthor($value, $load = true) Sets the current record's "Author" value
 * @method BlogArticle setId($value, $load = true) Sets the current record's "id" value
 *
 */
abstract class BaseBlogArticle extends Article
{

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BlogAuthor as Author', [
             'local' => 'blog_author_id',
             'foreign' => 'id']);
    }

}