<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseAttachment
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $file_path
 * @property string $id
 *
 */
abstract class BaseAttachment extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('attachment');
        $this->hasColumn('file_path', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getFilePath($load = true)
    {
        return $this->_get('file_path', $load);
    }

    /**
     * @param string $file_path
     * @param bool $load
     *
     * @return self
     */
    public function setFilePath($file_path, $load = true)
    {
        return $this->_set('file_path', $file_path, $load);
    }

    /**
     * @param bool $load
     *
     * @return integer
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param integer $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

}