<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseBlogAuthor
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property Doctrine_Collection $Articles
 * @property string $id
 *
 */
abstract class BaseBlogAuthor extends Author
{

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BlogArticle as Articles', [
             'local' => 'id',
             'foreign' => 'blog_author_id']);
    }

    /**
     * @param bool $load
     *
     * @return Doctrine_Collection
     */
    public function getArticles($load = true)
    {
        return $this->_get('Articles', $load);
    }

    /**
     * @param Doctrine_Collection $Articles
     * @param bool $load
     *
     * @return self
     */
    public function setArticles($Articles, $load = true)
    {
        return $this->_set('Articles', $Articles, $load);
    }

    /**
     * @param bool $load
     *
     * @return integer
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param integer $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

}