<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BasePermission
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $Groups
 * @property string $id
 *
 * @method string              getName($load = true) Returns the current record's "name" value
 * @method Doctrine_Collection getUsers($load = true) Returns the current record's "Users" collection
 * @method Doctrine_Collection getGroups($load = true) Returns the current record's "Groups" collection
 * @method string              getId($load = true) Returns the current record's "id" value
 * @method Permission          setName($value, $load = true) Sets the current record's "name" value
 * @method Permission          setUsers($value, $load = true) Sets the current record's "Users" collection
 * @method Permission          setGroups($value, $load = true) Sets the current record's "Groups" collection
 * @method Permission          setId($value, $load = true) Sets the current record's "id" value
 *
 */
abstract class BasePermission extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('permission');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User as Users', [
             'refClass' => 'UserPermission',
             'local' => 'permission_id',
             'foreign' => 'user_id']);

        $this->hasMany('Group as Groups', [
             'refClass' => 'GroupPermission',
             'local' => 'permission_id',
             'foreign' => 'group_id']);
    }

}