<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseUniqueTest
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $unique_test1
 * @property string $unique_test2
 * @property string $unique_test3
 * @property string $unique_test4
 * @property string $id
 *
 */
abstract class BaseUniqueTest extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('unique_test');
        $this->hasColumn('unique_test1', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('unique_test2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('unique_test3', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('unique_test4', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('unique_test', array(
             'fields' =>
             array(
              0 => 'unique_test1',
              1 => 'unique_test2',
             ),
             'type' => 'unique',
             ));
        $this->index('unique_test2', array(
             'fields' =>
             array(
              'unique_test4' =>
              array(
              'sorting' => 'ASC',
              'length' => '10',
              ),
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getUniqueTest1($load = true)
    {
        return $this->_get('unique_test1', $load);
    }

    /**
     * @param string $unique_test1
     * @param bool $load
     *
     * @return self
     */
    public function setUniqueTest1($unique_test1, $load = true)
    {
        return $this->_set('unique_test1', $unique_test1, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getUniqueTest2($load = true)
    {
        return $this->_get('unique_test2', $load);
    }

    /**
     * @param string $unique_test2
     * @param bool $load
     *
     * @return self
     */
    public function setUniqueTest2($unique_test2, $load = true)
    {
        return $this->_set('unique_test2', $unique_test2, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getUniqueTest3($load = true)
    {
        return $this->_get('unique_test3', $load);
    }

    /**
     * @param string $unique_test3
     * @param bool $load
     *
     * @return self
     */
    public function setUniqueTest3($unique_test3, $load = true)
    {
        return $this->_set('unique_test3', $unique_test3, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getUniqueTest4($load = true)
    {
        return $this->_get('unique_test4', $load);
    }

    /**
     * @param string $unique_test4
     * @param bool $load
     *
     * @return self
     */
    public function setUniqueTest4($unique_test4, $load = true)
    {
        return $this->_set('unique_test4', $unique_test4, $load);
    }

    /**
     * @param bool $load
     *
     * @return integer
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param integer $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

}