<?php

declare(strict_types=1);
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Subscription', 'doctrine2');

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseSubscription
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 * @property string $status
 * @property string $id
 *
 */
abstract class BaseSubscription extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('subscription');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' =>
             array(
              0 => 'New',
              1 => 'Active',
              2 => 'Pending',
              3 => 'Expired',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getName($load = true)
    {
        return $this->_get('name', $load);
    }

    /**
     * @param string $name
     * @param bool $load
     *
     * @return self
     */
    public function setName($name, $load = true)
    {
        return $this->_set('name', $name, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getStatus($load = true)
    {
        return $this->_get('status', $load);
    }

    /**
     * @param string $status
     * @param bool $load
     *
     * @return self
     */
    public function setStatus($status, $load = true)
    {
        return $this->_set('status', $status, $load);
    }

    /**
     * @param bool $load
     *
     * @return integer
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param integer $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

}