<?php

declare(strict_types=1);

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseCamelCase
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $article_id
 * @property string $testCamelCase
 * @property Article $Article
 * @property string $id
 *
 */
abstract class BaseCamelCase extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('camel_case');
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('testCamelCase', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', [
             'local' => 'article_id',
             'foreign' => 'id']);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getArticleId($load = true)
    {
        return $this->_get('article_id', $load);
    }

    /**
     * @param string $article_id
     * @param bool $load
     *
     * @return self
     */
    public function setArticleId($article_id, $load = true)
    {
        return $this->_set('article_id', $article_id, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getTestCamelCase($load = true)
    {
        return $this->_get('testCamelCase', $load);
    }

    /**
     * @param string $testCamelCase
     * @param bool $load
     *
     * @return self
     */
    public function setTestCamelCase($testCamelCase, $load = true)
    {
        return $this->_set('testCamelCase', $testCamelCase, $load);
    }

    /**
     * @param bool $load
     *
     * @return Article
     */
    public function getArticle($load = true)
    {
        return $this->_get('Article', $load);
    }

    /**
     * @param Article $Article
     * @param bool $load
     *
     * @return self
     */
    public function setArticle($Article, $load = true)
    {
        return $this->_set('Article', $Article, $load);
    }

    /**
     * @param bool $load
     *
     * @return integer
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param integer $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

}