<?php

declare(strict_types=1);

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseAuthorInheritanceConcrete
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $additional
 * @property string $id
 *
 */
abstract class BaseAuthorInheritanceConcrete extends Author
{

    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('author_inheritance_concrete');
        $this->hasColumn('additional', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setSubclasses($map)
    {
        $this->setTableName('author_inheritance_concrete');

        parent::setSubclasses($map);
    }

    public function setUp()
    {
        parent::setUp();
        
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getAdditional($load = true)
    {
        return $this->_get('additional', $load);
    }

    /**
     * @param string $additional
     * @param bool $load
     *
     * @return self
     */
    public function setAdditional($additional, $load = true)
    {
        return $this->_set('additional', $additional, $load);
    }

    /**
     * @param bool $load
     *
     * @return integer
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param integer $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

}