<?php

declare(strict_types=1);

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $username
 * @property string $password
 * @property string $test
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $Permissions
 * @property Profile $Profile
 * @property string $id
 *
 */
abstract class BaseUser extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('username', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('test', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Group as Groups', [
             'refClass' => 'UserGroup',
             'local' => 'user_id',
             'foreign' => 'group_id']);

        $this->hasMany('Permission as Permissions', [
             'refClass' => 'UserPermission',
             'local' => 'user_id',
             'foreign' => 'permission_id']);

        $this->hasOne('Profile', [
             'local' => 'id',
             'foreign' => 'user_id']);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getUsername($load = true)
    {
        return $this->_get('username', $load);
    }

    /**
     * @param string $username
     * @param bool $load
     *
     * @return self
     */
    public function setUsername($username, $load = true)
    {
        return $this->_set('username', $username, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getPassword($load = true)
    {
        return $this->_get('password', $load);
    }

    /**
     * @param string $password
     * @param bool $load
     *
     * @return self
     */
    public function setPassword($password, $load = true)
    {
        return $this->_set('password', $password, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getTest($load = true)
    {
        return $this->_get('test', $load);
    }

    /**
     * @param string $test
     * @param bool $load
     *
     * @return self
     */
    public function setTest($test, $load = true)
    {
        return $this->_set('test', $test, $load);
    }

    /**
     * @param bool $load
     *
     * @return Doctrine_Collection
     */
    public function getGroups($load = true)
    {
        return $this->_get('Groups', $load);
    }

    /**
     * @param Doctrine_Collection $Groups
     * @param bool $load
     *
     * @return self
     */
    public function setGroups($Groups, $load = true)
    {
        return $this->_set('Groups', $Groups, $load);
    }

    /**
     * @param bool $load
     *
     * @return Doctrine_Collection
     */
    public function getPermissions($load = true)
    {
        return $this->_get('Permissions', $load);
    }

    /**
     * @param Doctrine_Collection $Permissions
     * @param bool $load
     *
     * @return self
     */
    public function setPermissions($Permissions, $load = true)
    {
        return $this->_set('Permissions', $Permissions, $load);
    }

    /**
     * @param bool $load
     *
     * @return Profile
     */
    public function getProfile($load = true)
    {
        return $this->_get('Profile', $load);
    }

    /**
     * @param Profile $Profile
     * @param bool $load
     *
     * @return self
     */
    public function setProfile($Profile, $load = true)
    {
        return $this->_set('Profile', $Profile, $load);
    }

    /**
     * @param bool $load
     *
     * @return integer
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param integer $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

}