<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Subscription', 'doctrine2');

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseSubscription
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 * @property string $status
 * @property string $id
 *
 * @method string       getName($load = true) Returns the current record's "name" value
 * @method string       getStatus($load = true) Returns the current record's "status" value
 * @method string       getId($load = true) Returns the current record's "id" value
 * @method Subscription setName($value, $load = true) Sets the current record's "name" value
 * @method Subscription setStatus($value, $load = true) Sets the current record's "status" value
 * @method Subscription setId($value, $load = true) Sets the current record's "id" value
 *
 */
abstract class BaseSubscription extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('subscription');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' =>
             array(
              0 => 'New',
              1 => 'Active',
              2 => 'Pending',
              3 => 'Expired',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }

}