<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseResourceType
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $id
 * @property string $name
 *
 * @method string       getId($load = true) Returns the current record's "id" value
 * @method string       getName($load = true) Returns the current record's "name" value
 * @method ResourceType setId($value, $load = true) Sets the current record's "id" value
 * @method ResourceType setName($value, $load = true) Sets the current record's "name" value
 *
 */
abstract class BaseResourceType extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('resource_type');
        $this->hasColumn('id', 'enum', null, array(
             'type' => 'enum',
             'values' =>
             array(
              0 => 'type1',
              1 => 'type2',
              2 => 'type3',
             ),
             'primary' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }

}