<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseDefaultValueTest
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 * @property string $id
 *
 * @method string           getName($load = true) Returns the current record's "name" value
 * @method string           getId($load = true) Returns the current record's "id" value
 * @method DefaultValueTest setName($value, $load = true) Sets the current record's "name" value
 * @method DefaultValueTest setId($value, $load = true) Sets the current record's "id" value
 *
 */
abstract class BaseDefaultValueTest extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('default_value_test');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }

}