<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseBlogAuthor
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property Doctrine_Collection $Articles
 * @property string $id
 *
 * @method Doctrine_Collection getArticles($load = true) Returns the current record's "Articles" collection
 * @method string              getId($load = true) Returns the current record's "id" value
 * @method BlogAuthor          setArticles($value, $load = true) Sets the current record's "Articles" collection
 * @method BlogAuthor          setId($value, $load = true) Sets the current record's "id" value
 *
 */
abstract class BaseBlogAuthor extends Author
{

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BlogArticle as Articles', [
             'local' => 'id',
             'foreign' => 'blog_author_id']);
    }

}