<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseGroupPermission
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $group_id
 * @property string $permission_id
 *
 */
abstract class BaseGroupPermission extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('group_permission');
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('permission_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getGroupId($load = true)
    {
        return $this->_get('group_id', $load);
    }

    /**
     * @param string $group_id
     * @param bool $load
     *
     * @return self
     */
    public function setGroupId($group_id, $load = true)
    {
        return $this->_set('group_id', $group_id, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getPermissionId($load = true)
    {
        return $this->_get('permission_id', $load);
    }

    /**
     * @param string $permission_id
     * @param bool $load
     *
     * @return self
     */
    public function setPermissionId($permission_id, $load = true)
    {
        return $this->_set('permission_id', $permission_id, $load);
    }

}