<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseArticle
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $author_id
 * @property bool $is_on_homepage
 * @property string $title
 * @property string $body
 * @property string $test_column
 * @property string $views
 * @property string $type
 * @property Author $Author
 * @property Doctrine_Collection $camelCase
 * @property string $id
 *
 */
abstract class BaseArticle extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('article');
        $this->hasColumn('author_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_on_homepage', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('test_column', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('views', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->setSubClasses(array(
             'BlogArticle' =>
             array(
              'type' => 'BlogArticle',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Author', [
             'local' => 'author_id',
             'foreign' => 'id']);

        $this->hasMany('CamelCase as camelCase', [
             'local' => 'id',
             'foreign' => 'article_id']);

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' =>
             array(
              0 => 'title',
             ),
             'uniqueBy' =>
             array(
              0 => 'title',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getAuthorId($load = true)
    {
        return $this->_get('author_id', $load);
    }

    /**
     * @param string $author_id
     * @param bool $load
     *
     * @return self
     */
    public function setAuthorId($author_id, $load = true)
    {
        return $this->_set('author_id', $author_id, $load);
    }

    /**
     * @param bool $load
     *
     * @return bool
     */
    public function getIsOnHomepage($load = true)
    {
        return $this->_get('is_on_homepage', $load);
    }

    /**
     * @param bool $is_on_homepage
     * @param bool $load
     *
     * @return self
     */
    public function setIsOnHomepage($is_on_homepage, $load = true)
    {
        return $this->_set('is_on_homepage', $is_on_homepage, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getTitle($load = true)
    {
        return $this->_get('title', $load);
    }

    /**
     * @param string $title
     * @param bool $load
     *
     * @return self
     */
    public function setTitle($title, $load = true)
    {
        return $this->_set('title', $title, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getBody($load = true)
    {
        return $this->_get('body', $load);
    }

    /**
     * @param string $body
     * @param bool $load
     *
     * @return self
     */
    public function setBody($body, $load = true)
    {
        return $this->_set('body', $body, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getTestColumn($load = true)
    {
        return $this->_get('test_column', $load);
    }

    /**
     * @param string $test_column
     * @param bool $load
     *
     * @return self
     */
    public function setTestColumn($test_column, $load = true)
    {
        return $this->_set('test_column', $test_column, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getViews($load = true)
    {
        return $this->_get('views', $load);
    }

    /**
     * @param string $views
     * @param bool $load
     *
     * @return self
     */
    public function setViews($views, $load = true)
    {
        return $this->_set('views', $views, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getType($load = true)
    {
        return $this->_get('type', $load);
    }

    /**
     * @param string $type
     * @param bool $load
     *
     * @return self
     */
    public function setType($type, $load = true)
    {
        return $this->_set('type', $type, $load);
    }

    /**
     * @param bool $load
     *
     * @return Author
     */
    public function getAuthor($load = true)
    {
        return $this->_get('Author', $load);
    }

    /**
     * @param Author $Author
     * @param bool $load
     *
     * @return self
     */
    public function setAuthor($Author, $load = true)
    {
        return $this->_set('Author', $Author, $load);
    }

    /**
     * @param bool $load
     *
     * @return Doctrine_Collection
     */
    public function getCamelCase($load = true)
    {
        return $this->_get('camelCase', $load);
    }

    /**
     * @param Doctrine_Collection $camelCase
     * @param bool $load
     *
     * @return self
     */
    public function setCamelCase($camelCase, $load = true)
    {
        return $this->_set('camelCase', $camelCase, $load);
    }

    /**
     * @param bool $load
     *
     * @return integer
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param integer $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

}