<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**
 
 * BaseSetting
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 * @property string $value
 * @property string $weight
 * @property string $id
 *
 */
abstract class BaseSetting extends myDoctrineRecord
{

    public function setTableDefinition()
    {
        $this->setTableName('setting');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'notnull' => true,
             ));
        $this->hasColumn('value', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('weight', 'float', 4, array(
             'type' => 'float',
             'length' => 4,
             'scale' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' =>
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getName($load = true)
    {
        return $this->_get('name', $load);
    }

    /**
     * @param string $name
     * @param bool $load
     *
     * @return self
     */
    public function setName($name, $load = true)
    {
        return $this->_set('name', $name, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getValue($load = true)
    {
        return $this->_get('value', $load);
    }

    /**
     * @param string $value
     * @param bool $load
     *
     * @return self
     */
    public function setValue($value, $load = true)
    {
        return $this->_set('value', $value, $load);
    }

    /**
     * @param bool $load
     *
     * @return string
     */
    public function getWeight($load = true)
    {
        return $this->_get('weight', $load);
    }

    /**
     * @param string $weight
     * @param bool $load
     *
     * @return self
     */
    public function setWeight($weight, $load = true)
    {
        return $this->_set('weight', $weight, $load);
    }

    /**
     * @param bool $load
     *
     * @return integer
     */
    public function getId($load = true)
    {
        return $this->_get('id', $load);
    }

    /**
     * @param integer $id
     * @param bool $load
     *
     * @return self
     */
    public function setId($id, $load = true)
    {
        return $this->_set('id', $id, $load);
    }

}