<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User extends BaseUser
{
    public function setPassword($password, $load = true)
    {
        return $this->_set('password', md5($password), $load);
    }
}
